//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DatabaseServiceReference.WebServiceDatabaseSoap")]
    public interface WebServiceDatabaseSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        DatabaseServiceReference.loginResponse login(DatabaseServiceReference.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.loginResponse> loginAsync(DatabaseServiceReference.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        DatabaseServiceReference.GetUsersResponse GetUsers(DatabaseServiceReference.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.GetUsersResponse> GetUsersAsync(DatabaseServiceReference.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getQuestions", ReplyAction="*")]
        DatabaseServiceReference.getQuestionsResponse getQuestions(DatabaseServiceReference.getQuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getQuestions", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.getQuestionsResponse> getQuestionsAsync(DatabaseServiceReference.getQuestionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAnswers", ReplyAction="*")]
        DatabaseServiceReference.getAnswersResponse getAnswers(DatabaseServiceReference.getAnswersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAnswers", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.getAnswersResponse> getAnswersAsync(DatabaseServiceReference.getAnswersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWorkshops", ReplyAction="*")]
        DatabaseServiceReference.getWorkshopsResponse getWorkshops(DatabaseServiceReference.getWorkshopsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWorkshops", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.getWorkshopsResponse> getWorkshopsAsync(DatabaseServiceReference.getWorkshopsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteUser", ReplyAction="*")]
        DatabaseServiceReference.deleteUserResponse deleteUser(DatabaseServiceReference.deleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteUser", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.deleteUserResponse> deleteUserAsync(DatabaseServiceReference.deleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        DatabaseServiceReference.addUserResponse addUser(DatabaseServiceReference.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.addUserResponse> addUserAsync(DatabaseServiceReference.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUser", ReplyAction="*")]
        DatabaseServiceReference.updateUserResponse updateUser(DatabaseServiceReference.updateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.updateUserResponse> updateUserAsync(DatabaseServiceReference.updateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addQuestion", ReplyAction="*")]
        DatabaseServiceReference.addQuestionResponse addQuestion(DatabaseServiceReference.addQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addQuestion", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.addQuestionResponse> addQuestionAsync(DatabaseServiceReference.addQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteQuestion", ReplyAction="*")]
        DatabaseServiceReference.deleteQuestionResponse deleteQuestion(DatabaseServiceReference.deleteQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteQuestion", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.deleteQuestionResponse> deleteQuestionAsync(DatabaseServiceReference.deleteQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateQuestion", ReplyAction="*")]
        DatabaseServiceReference.updateQuestionResponse updateQuestion(DatabaseServiceReference.updateQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateQuestion", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.updateQuestionResponse> updateQuestionAsync(DatabaseServiceReference.updateQuestionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addAnswer", ReplyAction="*")]
        DatabaseServiceReference.addAnswerResponse addAnswer(DatabaseServiceReference.addAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addAnswer", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.addAnswerResponse> addAnswerAsync(DatabaseServiceReference.addAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAnswer", ReplyAction="*")]
        DatabaseServiceReference.deleteAnswerResponse deleteAnswer(DatabaseServiceReference.deleteAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAnswer", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.deleteAnswerResponse> deleteAnswerAsync(DatabaseServiceReference.deleteAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateAnswer", ReplyAction="*")]
        DatabaseServiceReference.updateAnswerResponse updateAnswer(DatabaseServiceReference.updateAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateAnswer", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.updateAnswerResponse> updateAnswerAsync(DatabaseServiceReference.updateAnswerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWorkshop", ReplyAction="*")]
        DatabaseServiceReference.addWorkshopResponse addWorkshop(DatabaseServiceReference.addWorkshopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addWorkshop", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.addWorkshopResponse> addWorkshopAsync(DatabaseServiceReference.addWorkshopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteWorkshop", ReplyAction="*")]
        DatabaseServiceReference.deleteWorkshopResponse deleteWorkshop(DatabaseServiceReference.deleteWorkshopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteWorkshop", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.deleteWorkshopResponse> deleteWorkshopAsync(DatabaseServiceReference.deleteWorkshopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateWorkshop", ReplyAction="*")]
        DatabaseServiceReference.updateWorkshopResponse updateWorkshop(DatabaseServiceReference.updateWorkshopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateWorkshop", ReplyAction="*")]
        System.Threading.Tasks.Task<DatabaseServiceReference.updateWorkshopResponse> updateWorkshopAsync(DatabaseServiceReference.updateWorkshopRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.loginRequestBody Body;
        
        public loginRequest()
        {
        }
        
        public loginRequest(DatabaseServiceReference.loginRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody()
        {
        }
        
        public loginRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.loginResponseBody Body;
        
        public loginResponse()
        {
        }
        
        public loginResponse(DatabaseServiceReference.loginResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody()
        {
        }
        
        public loginResponseBody(string loginResult)
        {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsers", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.GetUsersRequestBody Body;
        
        public GetUsersRequest()
        {
        }
        
        public GetUsersRequest(DatabaseServiceReference.GetUsersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetUsersRequestBody
    {
        
        public GetUsersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.GetUsersResponseBody Body;
        
        public GetUsersResponse()
        {
        }
        
        public GetUsersResponse(DatabaseServiceReference.GetUsersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DatabaseServiceReference.ArrayOfString GetUsersResult;
        
        public GetUsersResponseBody()
        {
        }
        
        public GetUsersResponseBody(DatabaseServiceReference.ArrayOfString GetUsersResult)
        {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getQuestionsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getQuestions", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.getQuestionsRequestBody Body;
        
        public getQuestionsRequest()
        {
        }
        
        public getQuestionsRequest(DatabaseServiceReference.getQuestionsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getQuestionsRequestBody
    {
        
        public getQuestionsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getQuestionsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getQuestionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.getQuestionsResponseBody Body;
        
        public getQuestionsResponse()
        {
        }
        
        public getQuestionsResponse(DatabaseServiceReference.getQuestionsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getQuestionsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DatabaseServiceReference.ArrayOfString getQuestionsResult;
        
        public getQuestionsResponseBody()
        {
        }
        
        public getQuestionsResponseBody(DatabaseServiceReference.ArrayOfString getQuestionsResult)
        {
            this.getQuestionsResult = getQuestionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAnswersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAnswers", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.getAnswersRequestBody Body;
        
        public getAnswersRequest()
        {
        }
        
        public getAnswersRequest(DatabaseServiceReference.getAnswersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAnswersRequestBody
    {
        
        public getAnswersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAnswersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAnswersResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.getAnswersResponseBody Body;
        
        public getAnswersResponse()
        {
        }
        
        public getAnswersResponse(DatabaseServiceReference.getAnswersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAnswersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DatabaseServiceReference.ArrayOfString getAnswersResult;
        
        public getAnswersResponseBody()
        {
        }
        
        public getAnswersResponseBody(DatabaseServiceReference.ArrayOfString getAnswersResult)
        {
            this.getAnswersResult = getAnswersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWorkshopsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWorkshops", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.getWorkshopsRequestBody Body;
        
        public getWorkshopsRequest()
        {
        }
        
        public getWorkshopsRequest(DatabaseServiceReference.getWorkshopsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getWorkshopsRequestBody
    {
        
        public getWorkshopsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWorkshopsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWorkshopsResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.getWorkshopsResponseBody Body;
        
        public getWorkshopsResponse()
        {
        }
        
        public getWorkshopsResponse(DatabaseServiceReference.getWorkshopsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWorkshopsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DatabaseServiceReference.ArrayOfString getWorkshopsResult;
        
        public getWorkshopsResponseBody()
        {
        }
        
        public getWorkshopsResponseBody(DatabaseServiceReference.ArrayOfString getWorkshopsResult)
        {
            this.getWorkshopsResult = getWorkshopsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteUser", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.deleteUserRequestBody Body;
        
        public deleteUserRequest()
        {
        }
        
        public deleteUserRequest(DatabaseServiceReference.deleteUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public deleteUserRequestBody()
        {
        }
        
        public deleteUserRequestBody(string username)
        {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.deleteUserResponseBody Body;
        
        public deleteUserResponse()
        {
        }
        
        public deleteUserResponse(DatabaseServiceReference.deleteUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteUserResponseBody
    {
        
        public deleteUserResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUser", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.addUserRequestBody Body;
        
        public addUserRequest()
        {
        }
        
        public addUserRequest(DatabaseServiceReference.addUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        public addUserRequestBody()
        {
        }
        
        public addUserRequestBody(int id, string username, string password, string firstName, string lastName, string email)
        {
            this.id = id;
            this.username = username;
            this.password = password;
            this.firstName = firstName;
            this.lastName = lastName;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.addUserResponseBody Body;
        
        public addUserResponse()
        {
        }
        
        public addUserResponse(DatabaseServiceReference.addUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addUserResponseBody
    {
        
        public addUserResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateUser", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.updateUserRequestBody Body;
        
        public updateUserRequest()
        {
        }
        
        public updateUserRequest(DatabaseServiceReference.updateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string findUsername;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        public updateUserRequestBody()
        {
        }
        
        public updateUserRequestBody(string findUsername, string username, string password, string firstName, string lastName, string email)
        {
            this.findUsername = findUsername;
            this.username = username;
            this.password = password;
            this.firstName = firstName;
            this.lastName = lastName;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.updateUserResponseBody Body;
        
        public updateUserResponse()
        {
        }
        
        public updateUserResponse(DatabaseServiceReference.updateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateUserResponseBody
    {
        
        public updateUserResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addQuestionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addQuestion", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.addQuestionRequestBody Body;
        
        public addQuestionRequest()
        {
        }
        
        public addQuestionRequest(DatabaseServiceReference.addQuestionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addQuestionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string question;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int qid;
        
        public addQuestionRequestBody()
        {
        }
        
        public addQuestionRequestBody(int id, string question, string username, int qid)
        {
            this.id = id;
            this.question = question;
            this.username = username;
            this.qid = qid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addQuestionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addQuestionResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.addQuestionResponseBody Body;
        
        public addQuestionResponse()
        {
        }
        
        public addQuestionResponse(DatabaseServiceReference.addQuestionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addQuestionResponseBody
    {
        
        public addQuestionResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteQuestion", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteQuestionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int qid;
        
        public deleteQuestionRequest()
        {
        }
        
        public deleteQuestionRequest(int qid)
        {
            this.qid = qid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteQuestionResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteQuestionResponse
    {
        
        public deleteQuestionResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateQuestionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateQuestion", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.updateQuestionRequestBody Body;
        
        public updateQuestionRequest()
        {
        }
        
        public updateQuestionRequest(DatabaseServiceReference.updateQuestionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateQuestionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string question;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        public updateQuestionRequestBody()
        {
        }
        
        public updateQuestionRequestBody(int id, string question, string user)
        {
            this.id = id;
            this.question = question;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateQuestionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateQuestionResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.updateQuestionResponseBody Body;
        
        public updateQuestionResponse()
        {
        }
        
        public updateQuestionResponse(DatabaseServiceReference.updateQuestionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateQuestionResponseBody
    {
        
        public updateQuestionResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAnswerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addAnswer", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.addAnswerRequestBody Body;
        
        public addAnswerRequest()
        {
        }
        
        public addAnswerRequest(DatabaseServiceReference.addAnswerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addAnswerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string answer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int qid;
        
        public addAnswerRequestBody()
        {
        }
        
        public addAnswerRequestBody(int id, string answer, string user, int qid)
        {
            this.id = id;
            this.answer = answer;
            this.user = user;
            this.qid = qid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAnswerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addAnswerResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.addAnswerResponseBody Body;
        
        public addAnswerResponse()
        {
        }
        
        public addAnswerResponse(DatabaseServiceReference.addAnswerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addAnswerResponseBody
    {
        
        public addAnswerResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteAnswer", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteAnswerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public deleteAnswerRequest()
        {
        }
        
        public deleteAnswerRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteAnswerResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class deleteAnswerResponse
    {
        
        public deleteAnswerResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAnswerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateAnswer", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.updateAnswerRequestBody Body;
        
        public updateAnswerRequest()
        {
        }
        
        public updateAnswerRequest(DatabaseServiceReference.updateAnswerRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateAnswerRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string answer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        public updateAnswerRequestBody()
        {
        }
        
        public updateAnswerRequestBody(int id, string answer, string user)
        {
            this.id = id;
            this.answer = answer;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAnswerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateAnswerResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.updateAnswerResponseBody Body;
        
        public updateAnswerResponse()
        {
        }
        
        public updateAnswerResponse(DatabaseServiceReference.updateAnswerResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateAnswerResponseBody
    {
        
        public updateAnswerResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWorkshopRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWorkshop", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.addWorkshopRequestBody Body;
        
        public addWorkshopRequest()
        {
        }
        
        public addWorkshopRequest(DatabaseServiceReference.addWorkshopRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addWorkshopRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string speakerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string imagePath;
        
        public addWorkshopRequestBody()
        {
        }
        
        public addWorkshopRequestBody(string name, string speakerName, System.DateTime date, string description, string imagePath)
        {
            this.name = name;
            this.speakerName = speakerName;
            this.date = date;
            this.description = description;
            this.imagePath = imagePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addWorkshopResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addWorkshopResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.addWorkshopResponseBody Body;
        
        public addWorkshopResponse()
        {
        }
        
        public addWorkshopResponse(DatabaseServiceReference.addWorkshopResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addWorkshopResponseBody
    {
        
        public addWorkshopResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteWorkshopRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteWorkshop", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.deleteWorkshopRequestBody Body;
        
        public deleteWorkshopRequest()
        {
        }
        
        public deleteWorkshopRequest(DatabaseServiceReference.deleteWorkshopRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteWorkshopRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public deleteWorkshopRequestBody()
        {
        }
        
        public deleteWorkshopRequestBody(string name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteWorkshopResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteWorkshopResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.deleteWorkshopResponseBody Body;
        
        public deleteWorkshopResponse()
        {
        }
        
        public deleteWorkshopResponse(DatabaseServiceReference.deleteWorkshopResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class deleteWorkshopResponseBody
    {
        
        public deleteWorkshopResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateWorkshopRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateWorkshop", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.updateWorkshopRequestBody Body;
        
        public updateWorkshopRequest()
        {
        }
        
        public updateWorkshopRequest(DatabaseServiceReference.updateWorkshopRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateWorkshopRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string speakerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string imagePath;
        
        public updateWorkshopRequestBody()
        {
        }
        
        public updateWorkshopRequestBody(string name, string speakerName, System.DateTime date, string description, string imagePath)
        {
            this.name = name;
            this.speakerName = speakerName;
            this.date = date;
            this.description = description;
            this.imagePath = imagePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateWorkshopResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateWorkshopResponse", Namespace="http://tempuri.org/", Order=0)]
        public DatabaseServiceReference.updateWorkshopResponseBody Body;
        
        public updateWorkshopResponse()
        {
        }
        
        public updateWorkshopResponse(DatabaseServiceReference.updateWorkshopResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateWorkshopResponseBody
    {
        
        public updateWorkshopResponseBody()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WebServiceDatabaseSoapChannel : DatabaseServiceReference.WebServiceDatabaseSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WebServiceDatabaseSoapClient : System.ServiceModel.ClientBase<DatabaseServiceReference.WebServiceDatabaseSoap>, DatabaseServiceReference.WebServiceDatabaseSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebServiceDatabaseSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebServiceDatabaseSoapClient.GetBindingForEndpoint(endpointConfiguration), WebServiceDatabaseSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceDatabaseSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebServiceDatabaseSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceDatabaseSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebServiceDatabaseSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebServiceDatabaseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public DatabaseServiceReference.loginResponse login(DatabaseServiceReference.loginRequest request)
        {
            return base.Channel.login(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.loginResponse> loginAsync(DatabaseServiceReference.loginRequest request)
        {
            return base.Channel.loginAsync(request);
        }
        
        public DatabaseServiceReference.GetUsersResponse GetUsers(DatabaseServiceReference.GetUsersRequest request)
        {
            return base.Channel.GetUsers(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.GetUsersResponse> GetUsersAsync(DatabaseServiceReference.GetUsersRequest request)
        {
            return base.Channel.GetUsersAsync(request);
        }
        
        public DatabaseServiceReference.getQuestionsResponse getQuestions(DatabaseServiceReference.getQuestionsRequest request)
        {
            return base.Channel.getQuestions(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.getQuestionsResponse> getQuestionsAsync(DatabaseServiceReference.getQuestionsRequest request)
        {
            return base.Channel.getQuestionsAsync(request);
        }
        
        public DatabaseServiceReference.getAnswersResponse getAnswers(DatabaseServiceReference.getAnswersRequest request)
        {
            return base.Channel.getAnswers(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.getAnswersResponse> getAnswersAsync(DatabaseServiceReference.getAnswersRequest request)
        {
            return base.Channel.getAnswersAsync(request);
        }
        
        public DatabaseServiceReference.getWorkshopsResponse getWorkshops(DatabaseServiceReference.getWorkshopsRequest request)
        {
            return base.Channel.getWorkshops(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.getWorkshopsResponse> getWorkshopsAsync(DatabaseServiceReference.getWorkshopsRequest request)
        {
            return base.Channel.getWorkshopsAsync(request);
        }
        
        public DatabaseServiceReference.deleteUserResponse deleteUser(DatabaseServiceReference.deleteUserRequest request)
        {
            return base.Channel.deleteUser(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.deleteUserResponse> deleteUserAsync(DatabaseServiceReference.deleteUserRequest request)
        {
            return base.Channel.deleteUserAsync(request);
        }
        
        public DatabaseServiceReference.addUserResponse addUser(DatabaseServiceReference.addUserRequest request)
        {
            return base.Channel.addUser(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.addUserResponse> addUserAsync(DatabaseServiceReference.addUserRequest request)
        {
            return base.Channel.addUserAsync(request);
        }
        
        public DatabaseServiceReference.updateUserResponse updateUser(DatabaseServiceReference.updateUserRequest request)
        {
            return base.Channel.updateUser(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.updateUserResponse> updateUserAsync(DatabaseServiceReference.updateUserRequest request)
        {
            return base.Channel.updateUserAsync(request);
        }
        
        public DatabaseServiceReference.addQuestionResponse addQuestion(DatabaseServiceReference.addQuestionRequest request)
        {
            return base.Channel.addQuestion(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.addQuestionResponse> addQuestionAsync(DatabaseServiceReference.addQuestionRequest request)
        {
            return base.Channel.addQuestionAsync(request);
        }
        
        public DatabaseServiceReference.deleteQuestionResponse deleteQuestion(DatabaseServiceReference.deleteQuestionRequest request)
        {
            return base.Channel.deleteQuestion(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.deleteQuestionResponse> deleteQuestionAsync(DatabaseServiceReference.deleteQuestionRequest request)
        {
            return base.Channel.deleteQuestionAsync(request);
        }
        
        public DatabaseServiceReference.updateQuestionResponse updateQuestion(DatabaseServiceReference.updateQuestionRequest request)
        {
            return base.Channel.updateQuestion(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.updateQuestionResponse> updateQuestionAsync(DatabaseServiceReference.updateQuestionRequest request)
        {
            return base.Channel.updateQuestionAsync(request);
        }
        
        public DatabaseServiceReference.addAnswerResponse addAnswer(DatabaseServiceReference.addAnswerRequest request)
        {
            return base.Channel.addAnswer(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.addAnswerResponse> addAnswerAsync(DatabaseServiceReference.addAnswerRequest request)
        {
            return base.Channel.addAnswerAsync(request);
        }
        
        public DatabaseServiceReference.deleteAnswerResponse deleteAnswer(DatabaseServiceReference.deleteAnswerRequest request)
        {
            return base.Channel.deleteAnswer(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.deleteAnswerResponse> deleteAnswerAsync(DatabaseServiceReference.deleteAnswerRequest request)
        {
            return base.Channel.deleteAnswerAsync(request);
        }
        
        public DatabaseServiceReference.updateAnswerResponse updateAnswer(DatabaseServiceReference.updateAnswerRequest request)
        {
            return base.Channel.updateAnswer(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.updateAnswerResponse> updateAnswerAsync(DatabaseServiceReference.updateAnswerRequest request)
        {
            return base.Channel.updateAnswerAsync(request);
        }
        
        public DatabaseServiceReference.addWorkshopResponse addWorkshop(DatabaseServiceReference.addWorkshopRequest request)
        {
            return base.Channel.addWorkshop(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.addWorkshopResponse> addWorkshopAsync(DatabaseServiceReference.addWorkshopRequest request)
        {
            return base.Channel.addWorkshopAsync(request);
        }
        
        public DatabaseServiceReference.deleteWorkshopResponse deleteWorkshop(DatabaseServiceReference.deleteWorkshopRequest request)
        {
            return base.Channel.deleteWorkshop(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.deleteWorkshopResponse> deleteWorkshopAsync(DatabaseServiceReference.deleteWorkshopRequest request)
        {
            return base.Channel.deleteWorkshopAsync(request);
        }
        
        public DatabaseServiceReference.updateWorkshopResponse updateWorkshop(DatabaseServiceReference.updateWorkshopRequest request)
        {
            return base.Channel.updateWorkshop(request);
        }
        
        public System.Threading.Tasks.Task<DatabaseServiceReference.updateWorkshopResponse> updateWorkshopAsync(DatabaseServiceReference.updateWorkshopRequest request)
        {
            return base.Channel.updateWorkshopAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceDatabaseSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceDatabaseSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebServiceDatabaseSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44338/WebServiceDatabase.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebServiceDatabaseSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44338/WebServiceDatabase.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebServiceDatabaseSoap,
            
            WebServiceDatabaseSoap12,
        }
    }
}
